server:
  port: 18080

spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          username: root
          password: tang
          url: jdbc:mysql://127.0.0.1:3306/tang?useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
#        slave:
#          username: root
#          password: tang
#          url: jdbc:mysql://192.168.2.159:3306/tang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
#          driver-class-name: com.mysql.cj.jdbc.Driver
      mp-enabled: true
  #dubbo
  dubbo:
    server: true
    application:
      id: biz-provider
      name: biz-provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 30880

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: org.tang.jsj.biz.provider.model

logging:
  level:
    org.tang.jsj: debug